env:
  global:
    - CC_TEST_REPORTER_ID=09ef3ee1379d0e592efde7047b322ffe26bc2ddc874753b311092db3f3250406

language: python
python: 3.6

install: make

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

before_install: 
    - pip install poetry
    - pip install coverage
    
script: 
    - make lint
    - make test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
