language: python
python: 3.6

install: make

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

before_install: 
    - pip install poetry
    - pip install pytest-cov
    
script: 
    - make lint
    - make test_cover

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
